# Fetching the latest node image on alpine linux
FROM node:alpine AS builder

# Declaring env
ENV NODE_ENV production

# Setting up the work directory
WORKDIR /client

# Installing dependencies
COPY ./package*.json .

RUN npm install

# Copying all the files in our project
COPY . .

# Prod configurations
RUN npm run build

FROM nginx
COPY --from=production /client/production /usr/share/nginx/html
