version: "3.8"
services:
  client:
    image: client-dev-i
    container_name: client-vps-c
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - frontend
    env_file: ./config/.env.client.dev
  server:
    image: server-dev-i
    container_name: server-vps-c
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend
    env_file: ./config/.env.server.dev
  mongodb:
    container_name: mongodb-vps-c
    image: mongo
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - backend
    command: [--auth]

volumes:
  mongodb:

networks:
  backend:
  frontend: