version: "3.8"
services:
  client:
    image: client-dev-i
    container_name: client-dev-c
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - NODE_ENV=development