# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Setting up the work directory
WORKDIR /client

# Installing dependencies
COPY ./package*.json .

RUN npm install

# Copying all the files in our project
COPY . .

#TODO - Change this to be an environment variable
EXPOSE 3000

# Starting our application
CMD ["npm","start"]